package com.flyrish.hades.dto;
// Generated 2014-7-1 18:11:49 by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * OFunc generated by hbm2java
 */
public class OFunc  implements java.io.Serializable {


     private BigDecimal funcid;
     private BigDecimal fatherid;
     private BigDecimal unitlevel;
     private String funcname;
     private String execfilename;
     private String execparameter;
     private String funcdesc;
     private String funcimage;
     private BigDecimal orderno;
     private BigDecimal layer;
     private Integer clickCount;
     private String userId;
     private String commonFuncId;
     /**
      * 0:update
      * 1:insert
      */
     private Integer updateOrInsertFlag;
     
    public String getCommonFuncId() {
		return commonFuncId;
	}
	public void setCommonFuncId(String commonFuncId) {
		this.commonFuncId = commonFuncId;
	}

	public Integer getUpdateOrInsertFlag() {
		return updateOrInsertFlag;
	}


	public void setUpdateOrInsertFlag(Integer updateOrInsertFlag) {
		this.updateOrInsertFlag = updateOrInsertFlag;
	}


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}


	public Integer getClickCount() {
		return clickCount;
	}


	public void setClickCount(Integer clickCount) {
		this.clickCount = clickCount;
	}


	public OFunc() {
    }

	
    public OFunc(BigDecimal fatherid, BigDecimal unitlevel, String funcname) {
        this.fatherid = fatherid;
        this.unitlevel = unitlevel;
        this.funcname = funcname;
    }
    public OFunc(BigDecimal fatherid, BigDecimal unitlevel, String funcname, String execfilename, String execparameter, String funcdesc, String funcimage, BigDecimal orderno, BigDecimal layer) {
       this.fatherid = fatherid;
       this.unitlevel = unitlevel;
       this.funcname = funcname;
       this.execfilename = execfilename;
       this.execparameter = execparameter;
       this.funcdesc = funcdesc;
       this.funcimage = funcimage;
       this.orderno = orderno;
       this.layer = layer;
    }
   
    public BigDecimal getFuncid() {
        return this.funcid;
    }
    
    public void setFuncid(BigDecimal funcid) {
        this.funcid = funcid;
    }
    public BigDecimal getFatherid() {
        return this.fatherid;
    }
    
    public void setFatherid(BigDecimal fatherid) {
        this.fatherid = fatherid;
    }
    public BigDecimal getUnitlevel() {
        return this.unitlevel;
    }
    
    public void setUnitlevel(BigDecimal unitlevel) {
        this.unitlevel = unitlevel;
    }
    public String getFuncname() {
        return this.funcname;
    }
    
    public void setFuncname(String funcname) {
        this.funcname = funcname;
    }
    public String getExecfilename() {
        return this.execfilename;
    }
    
    public void setExecfilename(String execfilename) {
        this.execfilename = execfilename;
    }
    public String getExecparameter() {
        return this.execparameter;
    }
    
    public void setExecparameter(String execparameter) {
        this.execparameter = execparameter;
    }
    public String getFuncdesc() {
        return this.funcdesc;
    }
    
    public void setFuncdesc(String funcdesc) {
        this.funcdesc = funcdesc;
    }
    public String getFuncimage() {
        return this.funcimage;
    }
    
    public void setFuncimage(String funcimage) {
        this.funcimage = funcimage;
    }
    public BigDecimal getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(BigDecimal orderno) {
        this.orderno = orderno;
    }
    public BigDecimal getLayer() {
        return this.layer;
    }
    
    public void setLayer(BigDecimal layer) {
        this.layer = layer;
    }
    public int compareTo(Object obj) {
    	if(obj==null) return -1;
    	return ((OFunc)obj).getClickCount().compareTo(this.clickCount);
    }

}


